### ISSUE TITLE
Game crashes on 1.20.1

### ISSUE THREAD

**Issue by iambeingtracked** [uku3lig/chathighlighter#8]
```
[11:02:28] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ClassCastException: class net.minecraft.class_327 cannot be cast to class net.minecraft.class_332 (net.minecraft.class_327 and net.minecraft.class_332 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @221af3c0)
	at net.minecraft.class_338.args$zjh000$chathighlighter$highlight(class_338.java:1077) ~[client-intermediary.jar:?]
	at net.minecraft.class_338.method_1805(class_338.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:357) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:926) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
[11:02:29] [Render thread/INFO]: Stopping worker threads
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-06-18 11:02:29
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_327 cannot be cast to class net.minecraft.class_332 (net.minecraft.class_327 and net.minecraft.class_332 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @221af3c0)
	at net.minecraft.class_338.args$zjh000$chathighlighter$highlight(class_338.java:1077)
	at net.minecraft.class_338.method_1805(class_338.java:130)
	at net.minecraft.class_329.method_1753(class_329.java:357)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_338.args$zjh000$chathighlighter$highlight(class_338.java:1077)
	at net.minecraft.class_338.method_1805(class_338.java:130)
	at net.minecraft.class_329.method_1753(class_329.java:357)

```

**Comment by uku3lig** [comment]
thank you for the report, i'm stupid.

**Comment by iambeingtracked** [comment]
thank you for fixing homie
